### ISSUE TITLE
pre-trained model [ENPAR] ,link is invalid

### ISSUE THREAD

**Issue by maoyingmy** [Receiling/ENPAR#1]
The pre-trained model [ENPAR](https://pan.baidu.com/s/1ice6IkZFBQhSl8LMhf-Chg)(password: 2imb)   ,The corresponding link is invalid.
Can you share the link again?

**Comment by Receiling** [comment]
Sorry, we have updated the download link.

**Comment by maoyingmy** [comment]
Thank you for sharing
